version: '3.8'
services:
  web:
    image: show-time/web
    build: 
      context: ./web
      dockerfile: ./Dockerfile
    ports: 
      - '4200:80'
    depends_on:
      - api

  api:
    image: show-time/api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'